name: Terraform EC2 

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Deployement
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Artifact
        run: ls -ltra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "${{ secrets.REGION }}" 
      - name: Create terraform.tfvars from secrets
        run: |
            cat > terraform.tfvars <<EOF
            region      =       "${{ secrets.REGION }}" 
            ami               = "${{ secrets.AMI }}"
            instance_type     = "${{ secrets.INSTANCE_TYPE }}"
            key_name                = "kunle-vpc-deployer-key"
            vpc_name          = "${{ secrets.VPC_NAME }}" 
            instance-name-ansible = "${{ secrets.INSTANCE_NAME_ANSIBLE }}"
            instance-name-nginx = "${{ secrets.INSTANCE_NAME_NGINX }}"
            instance-name-java = "${{ secrets.INSTANCE_NAME_JAVA }}"
            EOF
       
      - name: Display terraform.tfvars
        run: cat terraform.tfvars

      - name: Prep Terraform Binaries
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Terraform Init
        #working-directory: . #terraform
        run: terraform init

      - name: Terraform Validate
        #working-directory: . #terraform
        run: terraform validate

      - name: Terraform plan 
       #working-directory: terraform
        run: terraform plan

      - name: Terraform apply 
        ##working-directory: terraform
        run: terraform destroy -auto-approve
        #run: terraform apply -auto-approve
      